import os

CONFIRMATION_TOKEN = os.environ.get('CONFIRMATION_TOKEN')
VK_API_TOKEN = os.environ.get('VK_API_TOKEN')
VK_CALLBACK_SECRET = os.environ.get('VK_CALLBACK_SECRET')
WEBHOOK_SECRET = os.environ.get('WEBHOOK_SECRET')
